//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Packed_Lunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cardapio
    {
        public int Id_Cardapio { get; set; }
        public Nullable<System.DateTime> Data_Fim { get; set; }
        public Nullable<System.DateTime> Data_ini { get; set; }
        public Nullable<int> Id_Restaurante_fk { get; set; }
    
        public virtual Restaurante Restaurante { get; set; }
    }
}
