
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Packed_Lunch.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Empresa
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Empresa()
    {

        this.Pessoas = new HashSet<Pessoa>();

        this.Pedidoes = new HashSet<Pedido>();

    }


    public int Id_Empresa { get; set; }

    public string Cnpj { get; set; }

    public string Nome { get; set; }

    public string Endereco { get; set; }

    public string Cidade { get; set; }

    public string Telefone { get; set; }

    public string Login { get; set; }

    public string Senha { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pessoa> Pessoas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pedido> Pedidoes { get; set; }

}

}
