

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Packed_Lunch.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class Packed_Lunch_4_1Entities : DbContext
{
    public Packed_Lunch_4_1Entities()
        : base("name=Packed_Lunch_4_1Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Cardapio> Cardapios { get; set; }

    public virtual DbSet<Empresa> Empresas { get; set; }

    public virtual DbSet<Entrega> Entregas { get; set; }

    public virtual DbSet<Entregador> Entregadors { get; set; }

    public virtual DbSet<Horario_limite> Horario_limite { get; set; }

    public virtual DbSet<Pedido> Pedidoes { get; set; }

    public virtual DbSet<Pessoa> Pessoas { get; set; }

    public virtual DbSet<Produto> Produtoes { get; set; }

    public virtual DbSet<Restaurante> Restaurantes { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Compoem> Compoems { get; set; }



    public virtual ObjectResult<Select_empresa_Result> Select_empresa(Nullable<int> id_empresa)
    {

        var id_empresaParameter = id_empresa.HasValue ?
            new ObjectParameter("Id_empresa", id_empresa) :
            new ObjectParameter("Id_empresa", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_empresa_Result>("Select_empresa", id_empresaParameter);
    }


    public virtual ObjectResult<Select_pedidos_empresa_Result> Select_pedidos_empresa(Nullable<int> id_empresa)
    {

        var id_empresaParameter = id_empresa.HasValue ?
            new ObjectParameter("Id_empresa", id_empresa) :
            new ObjectParameter("Id_empresa", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_pedidos_empresa_Result>("Select_pedidos_empresa", id_empresaParameter);
    }

}

}

