//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Packed_Lunch.Models
{
    public class Possui2
    {
        public int Qtd { get; set; }
        public string Observações { get; set; }
        public int Id_Produto_fk { get; set; }
        public int Id_Pedido_fk { get; set; }


    }
}